### ISSUE TITLE
docker-compose up -dで swagger関連のサービスにアクセスできない

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/auto-matching#141]
docker-compseで立ち上げたserverにアクセすすると、
err_empty_respose　というエラーとなりブラウザでなにも表示されません。
この事象の奇妙なところはdockerをつかうと表示されるということです。
なので、docker-composeで頑張らずにdockerで回避しようかなと考えていたところでした。
https://github.com/tsu-nera/auto-matching/pull/140/files#diff-4e5e90c6228fd48698d074241c2ba760R59
このへんの修正ですねー。
LInuxでもMacでも発生するので、個別の環境ではなくてdockerのネットワークの設定だと思うのですが、ネットで検索してもあまり類似の情報かないですね。

**Comment by tsu-nera** [comment]
とりあえず、dockerで起動できるようなので、これで回避。

**Comment by yoneapp** [comment]
```
$ docker-compose down
Stopping auto-matching_swagger-ui_1      ... done
Stopping auto-matching_swagger-editor_1  ... done
Stopping auto-matching_redis_1           ... done
Stopping auto-matching_selenium-server_1 ... done
Stopping auto-matching_swagger-api_1     ... done
Stopping auto-matching_postgres_1        ... done
Removing auto-matching_rails_1           ... done
Removing auto-matching_nuxt_1            ... done
Removing auto-matching_swagger-ui_1      ... done
Removing auto-matching_swagger-editor_1  ... done
Removing auto-matching_redis_1           ... done
Removing auto-matching_nuxt-test_1       ... done
Removing auto-matching_selenium-server_1 ... done
Removing auto-matching_swagger-api_1     ... done
Removing auto-matching_postgres_1        ... done
Removing network auto-matching_default
```

この状態で

```
$ open http://localhost:8001/
```

してみたところ表示することが出来ました。

<img width="1139" alt="2018-12-16 19 38 36" src="https://user-images.githubusercontent.com/592748/50052660-e0220d80-016a-11e9-87a5-1eb67d783454.png">

ただ、ここでリロードすると

<img width="1078" alt="2018-12-16 19 44 42" src="https://user-images.githubusercontent.com/592748/50052668-0f387f00-016b-11e9-8db4-2850481d710a.png">

となるようでした。
この現象はちょっと気になりますね。

**Comment by yoneapp** [comment]
> ```
> docker pull swaggerapi/swagger-editor
> docker run -d -p 80:8080 swaggerapi/swagger-editor
> ```
> https://hub.docker.com/r/swaggerapi/swagger-editor/

こちら`image: swaggerapi/swagger-editor`のドキュメントになります。

> ```
>  swagger-editor:
>    image: swaggerapi/swagger-editor
>    ports:
>      - 8081:8000
> ```
> https://github.com/tsu-nera/auto-matching/pull/140/files#diff-4e5e90c6228fd48698d074241c2ba760R59

コードを見るとポート番号が違うくて8000版でもアクセスできるのは結構謎なんですが
8080ポートに向けたら私の環境では動きました。

**Comment by yoneapp** [comment]
一回だけアクセス出来る理由はブラウザキャッシュの可能性があります。
https://twitter.com/kimihiro_n/status/1074286732202323968

**Comment by tsu-nera** [comment]
8000でアクセスはブラウザキャッシュの可能性あり。

@yoneapp 
私の環境でも8080でアクセスできました。私のドキュメントのミスリードで8000を設定していたようです。解決方法を教えていただきありがとうございます。助かりました。

**Comment by tsu-nera** [comment]
https://github.com/tsu-nera/auto-matching/pull/140/commits/4b47228ec7cb6c3f0e51cb7bfabb45635817508d

にて解決しましたので、closeします。
