### ISSUE TITLE
[場所変更]次回打ち合わせ 2018/1/19(土) 12: 00 新宿ルノアール

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/auto-matching#229]
http://www.komeda.co.jp/search/shopdetail.php?id=808

### 話すこと

- [x] 進捗の確認
- [x] 予定の確認
- [x] 次回打ち合わせの日と場所を決める
- [x] 完成した掲示板投稿機能のデモ
- [x] tokiさんとの顔合わせ
- [x] スクレイピング対象サイトのデモ
- [x] プロジェクト構造の説明 
- [x] GitHubの使いかたの説明

**Comment by Goi666** [comment]
店舗予備（新宿）
https://goworkship.com/magazine/shinjuku-nomado/

**Comment by tsu-nera** [comment]
場所を変更します。
https://tabelog.com/tokyo/A1304/A130401/13113417/

**Comment by tsu-nera** [comment]
来週か再来週。

**Comment by tsu-nera** [comment]
- 文字列はそのままで保存
- マニュアルの定期実行
- 東京、今スグ会いたい、以外を選択。
